# Generated by Django 5.1.4 on 2024-12-17 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vasques_sergioAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='hora_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
