# Generated by Django 5.1.4 on 2024-12-18 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vasques_sergioAPP', '0003_remove_inscripcion_profesion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion', '-hora_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Puede dejar este campo en blanco.', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='email',
            field=models.EmailField(help_text='Ingrese un correo electrónico válido.', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], help_text='Seleccione el estado de la inscripción.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Se asigna automáticamente la fecha actual.', verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='hora_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Se asigna automáticamente la hora actual.', verbose_name='Hora de Inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='institucion',
            field=models.ForeignKey(help_text='Seleccione la institución correspondiente.', on_delete=django.db.models.deletion.CASCADE, to='Vasques_sergioAPP.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre completo del participante.', max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_personas',
            field=models.IntegerField(help_text='Cantidad de personas entre 1 y 30.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Número de Personas'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(help_text='Ingrese el número de contacto del participante.', max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(help_text='Ingrese la dirección completa.', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(help_text='Máximo 80 caracteres.', max_length=80, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(help_text='Número de contacto.', max_length=15, verbose_name='Teléfono'),
        ),
    ]
